
import openai
from flask import Flask, request, jsonify

# Configura tu clave de API de OpenAI
openai.api_key = "TU_CLAVE_API"

app = Flask(__name__)

@app.route('/chatgpt', methods=['POST'])
def chat_gpt():
    user_input = request.json.get('message')

    if not user_input:
        return jsonify({"error": "No message provided"}), 400

    # Llamada a la API de OpenAI
    try:
        response = openai.Completion.create(
            engine="text-davinci-003",  # O puedes usar GPT-4 si tienes acceso
            prompt=user_input,
            max_tokens=100
        )
        message = response['choices'][0]['text'].strip()
        return jsonify({"response": message}), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 500


app= Flask(__name__)

paquetes_dias_completos = [ 
    {"id":1, "destino": "Peninsula Valdez", "descripcion": "¡Prepárate para una aventura inolvidable en la maravillosa Península Valdés! Comenzamos temprano, entre las 07:30 y 08:00 de la mañana, cuando te recogemos en tu alojamiento en Puerto Madryn. Desde ahí, nos lanzamos a la ruta, recorriendo 40 km por la pintoresca RP Nº1 hasta conectarnos con la RP Nº2, rumbo a nuestra primera parada: el Puesto de Control 'El Desempeño'. Aquí haremos una breve pausa para abonar el ingreso a la reserva (¡no olvides llevar efectivo ya que en esta zona no hay señal de internet ni medios electrónicos!). Nuestra próxima parada será el Centro de Interpretación del Istmo Carlos Ameghino. Aquí te espera una fascinante exposición de piezas rescatadas del Fuerte San José y paneles que revelan la fauna y flora de la Península Valdés, incluyendo el imponente esqueleto de una Ballena Franca Austral. ¡Un verdadero banquete para los curiosos amantes de la naturaleza! Luego, nos dirigimos a la encantadora localidad de Puerto Pirámides, a solo 20 km de distancia. Aquí tendrás la oportunidad de embarcarte en una aventura de avistaje de ballenas (según la temporada, ¡opcional!) o simplemente explorar esta pintoresca villa turística a tu ritmo. Pero la aventura no termina ahí. Continuamos hacia Caleta Valdés, a unos 75 km, donde el paisaje te robará el aliento. Durante el trayecto, mantén los ojos abiertos para avistar guanacos, choiques, maras y zorros grises que habitan la región. Al llegar, serás testigo de los apostaderos de los imponentes Elefantes Marinos del Sur, donde podrás observar su comportamiento en su hábitat natural. Si el hambre llama, podrás disfrutar de un almuerzo (no incluido) en el parador local con vistas espectaculares. Finalmente, nos dirigimos más al norte, a unos 45 km, hasta llegar a Punta Norte, el punto culminante de nuestra travesía. Según la época del año, aquí podrás ver elefantes marinos, lobos marinos y, con un poco de suerte, ¡incluso Orcas! Este área, declarada Patrimonio Natural de la Humanidad por la UNESCO, es el broche de oro de nuestra aventura. Cerca de las 18:00/18:30, regresaremos a Puerto Madryn, concluyendo una jornada llena de naturaleza, fauna y paisajes impresionantes. ¡Te esperamos para vivir esta experiencia única!"},

    {"id":2, "destino":"Punta Tombo", "descripcion": "¡Prepárate para una experiencia única! La apertura estimada de la reserva es el 15/09. Comenzamos el día buscándote por tu alojamiento en Puerto Madryn entre las 07:30 y 08:00 hs, ¡y nos lanzamos a la aventura! Partimos hacia el sur por la RN N°3, recorriendo unos 180 km llenos de paisajes patagónicos, hasta llegar a la increíble reserva de Punta Tombo, hogar de la mayor colonia de pingüinos de Magallanes. Hacemos una breve pausa para abonar el ingreso (¡recuerda llevar efectivo ya que no hay señal de internet aquí!). Después, exploraremos el centro de visitantes donde aprenderemos sobre el origen del nombre 'Tombo', el fascinante ciclo de vida de los pingüinos y su hábitat marino. ¡Y aquí llega el momento más emocionante! Los senderos y miradores nos invitan a caminar entre estos curiosos pingüinos mientras observamos sus nidos, cuevas, huevos y hasta escuchamos sus peculiares graznidos. Cada paso es una nueva aventura, llena de vida y energía. Tras recorrer la reserva, ponemos rumbo a Gaiman, una pintoresca colonia galesa donde la historia cobra vida en su arquitectura. Para quienes deseen algo dulce, podrán disfrutar del tradicional té galés con deliciosas tortas y tartas, pan y manteca caseros, dulces y sándwiches (opcional, no incluido). Finalmente, regresamos a Puerto Madryn cerca de las 18:00 hs, ¡con la mochila llena de recuerdos inolvidables! Fin de los servicios."},
    
    {"id":3,"destino":"Dique Ameghino", "Descripcion": "¡Prepárate para un día lleno de sorpresas y paisajes impresionantes! Comenzamos buscándote por tu alojamiento en Puerto Madryn entre las 07:30 y 08:00 hs, y nos ponemos en marcha. Nuestro destino es un rincón poco conocido pero lleno de paz y belleza: la villa de Dique Florentino Ameghino, donde la tranquilidad y la naturaleza te envolverán. Partimos por la RN N°3, pasando por Trelew, y luego tomamos la RN Nº25 rumbo al dique. En esta pequeña villa, te sorprenderás con la majestuosidad de la obra de ingeniería que combina los colores de las rocas y las aguas cristalinas del Río Chubut. Aquí empieza la verdadera aventura: realizaremos un trekking que nos llevará por los murallones y a través de un túnel hasta el mismo dique, desde donde tendremos una vista espectacular de la localidad. Durante nuestro recorrido, descubriremos maravillas naturales como la cueva de los leones, la cascada, la gruta de la virgen y los depósitos de caolín, ¡e incluso veremos una colada de volcán! Haremos una pausa para descansar y disfrutar de un almuerzo (no incluido), rodeados de este paisaje único. Tras un día explorando el impresionante valle del Río Chubut, regresaremos a Puerto Madryn, llegando aproximadamente a las 18:00 hs. ¡Un día lleno de descubrimientos y paisajes inolvidables! Fin de los servicios."}
    ]

excursiones_medio_dia= [
    {"id":1, "destino":"doradillo", "descripcion": "¡Prepárate para una experiencia única y cercana a la naturaleza! Te buscamos en tu alojamiento en Puerto Madryn en el horario coordinado y comenzamos nuestro emocionante recorrido. A tan solo 15 km de la ciudad, nos espera un lugar especial donde las ballenas son las verdaderas protagonistas. Después de una corta caminata hacia la costa, nos encontraremos frente a estos majestuosos animales en su hábitat natural, ¡tan cerca que sentirás que casi puedes tocarlas! Este sitio privilegiado ofrece una vista inigualable del avistaje costero, donde las ballenas saltan, muestran sus aletas, colas y juegan con sus crías, adueñándose del escenario. La conexión con la naturaleza es total, dejándote inmerso en la magia del momento. Tras disfrutar de esta experiencia inolvidable, regresamos a la ciudad. Recuerda que el horario de esta aventura depende de la marea, y la duración total es de aproximadamente 3 horas. ¡No te pierdas esta oportunidad única!"},

    {"id":2,"destino":"Valle Infeior","descripcion": "¡Embárcate en un fascinante viaje a través del tiempo y las culturas! Te recogemos en tu alojamiento en Puerto Madryn en el horario coordinado para iniciar un recorrido lleno de historia y sorpresas. Nuestro primer destino es la ciudad de Trelew, donde exploraremos el famoso museo Paleontológico Egidio Feruglio (opcional, entrada no incluida). Aquí, nos sumergiremos en el asombroso mundo de la prehistoria, observando fósiles de criaturas que habitaron la Patagonia hace millones de años. ¡Incluso podremos ver a los paleontólogos trabajando en vivo en el laboratorio! Después, continuamos nuestro paseo hacia Gaiman, una encantadora colonia galesa que mantiene intacta su esencia y costumbres. En este pintoresco pueblo, recorreremos lugares históricos y culturales como la primera casa, el Colegio Camwy, la plaza central y el túnel del ferrocarril, entre otros tesoros patrimoniales. Y, para quienes deseen una experiencia aún más dulce, podrán disfrutar del tradicional té galés con exquisitas delicias caseras (opcional, no incluido). Tras un día lleno de historia y cultura, regresamos a Puerto Madryn, con el corazón y la mente llenos de recuerdos inolvidables. Fin de los servicios."},

    {"id":3, "destino":"Mar y Ballenas","descripcion": "¡Prepárate para una jornada de pura naturaleza y aventura! Te recogemos en tu alojamiento en Puerto Madryn en el horario coordinado, y arrancamos nuestro recorrido. Comenzamos transitando 40 km por la RP Nº1, luego tomamos la RP N°2 hacia el Puesto de Control 'El Desempeño', donde haremos una breve parada para abonar el ingreso a la reserva (¡recuerda que solo se puede pagar en efectivo, ya que en esta zona no hay señal de internet!). Continuamos hacia nuestro primer destino, el centro de interpretación del Istmo Carlos Ameghino. Allí, nos esperan fascinantes exposiciones de fauna y flora de la Península Valdés, piezas históricas del Fuerte San José, y el imponente esqueleto de una Ballena Franca Austral. ¡Un imperdible para los amantes de la naturaleza! Luego, seguimos hacia la pintoresca villa de Puerto Pirámides, donde la verdadera aventura comienza. Aquí nos embarcaremos para vivir la emocionante experiencia del avistaje de ballenas, donde estas majestuosas criaturas se acercarán a nosotros mostrando sus colas, saltos y juegos en total libertad. Cada movimiento será una sorpresa que te dejará recuerdos para toda la vida. Después de este increíble encuentro, nos dirigimos a la lobería de Punta Pirámide, donde contemplaremos la energía vibrante de los lobos marinos en su entorno natural, rodeados de un paisaje espectacular. Finalmente, emprendemos el regreso a Puerto Madryn, llenos de recuerdos inolvidables. Fin de los servicios."},

    {"id":4,"Destino": "Punta Loma","Descripcion": "¡Prepárate para un día lleno de descubrimientos y vistas inolvidables! Te recogemos en tu alojamiento en Puerto Madryn en el horario acordado, y arrancamos nuestra excursión con un breve city tour, recorriendo los puntos más emblemáticos de la ciudad. A lo largo del recorrido, disfrutarás de panorámicas impresionantes mientras te sumerges en la historia y la cultura local. Después, nos dirigimos hacia el sur, recorriendo unos 20 km hasta llegar a la fascinante reserva de Punta Loma. Aquí, tendrás la oportunidad de explorar dos senderos únicos. El primero, de unos 500 metros, nos invita a conocer la flora endémica del lugar mientras caminamos hacia un mirador con vistas espectaculares. El segundo sendero nos lleva al mirador principal, donde la estrella del espectáculo es la colonia de lobos marinos. Desde aquí, podrás observar de cerca su comportamiento: los cachorros jugando, los adultos descansando, mientras aves como los cormoranes sobrevuelan o anidan en los acantilados. Deja que todos tus sentidos se involucren: el rugido del mar, el viento en tu piel, y los sonidos de la vida silvestre a tu alrededor crean una experiencia inolvidable. Finalmente, regresamos a Puerto Madryn, con el corazón lleno de recuerdos inolvidables. Fin de los servicios."}

]

nautica_turismo_aventura= [
    {"id":1,"Actividad":"Excursiones de ballenas", "descripcion": "¡Prepara tus sentidos para una experiencia única! Esta actividad puede combinarse perfectamente con la excursión Península Valdés o Mar y Ballenas, o si lo prefieres, puedes dirigirte por tu cuenta a Puerto Pirámides después de coordinar con nosotros el turno de navegación. El preembarque comienza media hora antes de la salida asignada, donde te prepararemos para embarcar: colocación de chalecos salvavidas, entrega de tarjetas de embarque, y capas de lluvia si es necesario. ¡Luego empieza la verdadera magia! Nos embarcamos para avistar ballenas en su hábitat natural. Al ser animales en libertad, los acercamientos dependen de su curiosidad y voluntad, ¡lo que hace que cada avistaje sea completamente único! Ten en cuenta que, como toda actividad náutica, la salida está sujeta a las condiciones climáticas y puede reprogramarse si es necesario. INICIO ESTIMADO DE TEMPORADA: 15 DE JUNIO, FIN ESTIMADO DE TEMPORADA: PRINCIPIOS DE DICIEMBRE."},

    {"id":2,"Actividad":"paseo nautico","descripcion":"¡Prepárate para una aventura inolvidable en el mar! El recorrido comienza desde el Muelle Piedrabuena, adentrándonos en el Golfo Nuevo, alejándonos unos pocos kilómetros de la ciudad para iniciar la emocionante búsqueda de delfines. Una vez que los localizamos, nos acercamos a baja velocidad y son los propios delfines quienes se encargan de hacer contacto, acercándose juguetonamente a la embarcación, realizando saltos y acrobacias que te dejarán sin aliento. Tras disfrutar de 1 a 1:30 horas de interacción con estos increíbles animales en su hábitat natural, nos dirigimos a la Lobería de Punta Loma, donde podrás observar lobos marinos en estado salvaje y una variedad de aves, como los cormoranes, en un entorno espectacular. Como toda actividad náutica, esta excursión está sujeta a las condiciones climáticas, por lo que puede reprogramarse si es necesario. INICIO ESTIMADO DE TEMPORADA: PRINCIPIOS DE ENERO, FIN ESTIMADO DE TEMPORADA: MARZO."},

    {"id":3,"activad":"snorkeling", "descripcion": "¡Prepárate para una experiencia inolvidable bajo el mar! La actividad comienza en el local de nuestro operador, donde nos equipamos con trajes isotérmicos de 7 mm. Luego nos dirigimos a la playa para embarcarnos en esta aventura. Durante el viaje, el instructor nos dará una charla informativa sobre el equipo y cómo será el contacto con los lobos marinos. Nuestro destino es la Reserva Natural Punta Loma, hogar de un apostadero permanente de lobos marinos de un pelo. Una vez allí, pasaremos entre 45 y 50 minutos en el agua, siempre acompañados por un instructor que se asegurará de que la interacción sea segura y respetuosa. ¡Y lo mejor de todo es que toda la experiencia será grabada en video! La interacción con los lobos marinos depende de ellos, pero suelen ser criaturas curiosas y sociables, lo que hace que estar cerca de ellos sea una experiencia fascinante. Puerto Madryn nos brinda la oportunidad única de sumergirnos y jugar con esta maravillosa especie en su hábitat natural. ¡Y no te preocupes, no es necesario saber nadar! Como toda actividad náutica, la excursión está sujeta a las condiciones climáticas, por lo que puede reprogramarse si es necesario."},

    {"id":4,"actividad":"kayak costero", "descripcion": "¡Reserva con 48 horas de anticipación y prepárate para una aventura inolvidable en kayak! En esta travesía costera, recorreremos parte del Golfo Nuevo bordeando la costa de la ciudad. Es una experiencia accesible para todos, no necesitas conocimientos previos, solo ¡las ganas de lanzarte a la aventura! Te proporcionamos todo el equipo necesario (remos, chalecos salvavidas, cascos, etc.), y antes de comenzar, nuestro guía especializado te dará una charla informativa para garantizar que disfrutes del mar con total seguridad. La salida suele programarse en las primeras horas de la mañana, momento ideal para explorar el mar y obtener una vista espectacular de la ciudad y sus alrededores. Nuestro guía no solo te llevará por esta emocionante travesía, sino que también compartirá información fascinante sobre la región, su geografía, historia y los recursos naturales que hacen de Puerto Madryn un lugar único. Remaremos hasta llegar a Punta Cuevas, donde haremos una pausa para descansar, disfrutar de un snack y absorber la belleza del entorno antes de emprender el regreso. Aunque no se garantiza el avistaje de fauna, en ciertas épocas del año podrías tener la suerte de cruzarte con lobos marinos, pingüinos o incluso ballenas francas australes. Como toda actividad náutica, la excursión depende de las condiciones climáticas, por lo que podría estar sujeta a reprogramación. Las excursiones en kayak, debido a la exigencia física, son aptas solo para personas entre 15 y 70 años de edad con buen estado físico. NO deberán participar: personas con sobrepeso (hasta 1.70 mts - 90 kg, hasta 1.80 mts - 100 kg, hasta 1.90 mts - 120 kg), mujeres embarazadas, personas con cualquier grado o tipo de discapacidad física o mental que afecte su atención, marcha o coordinación, personas que sufran enfermedades cardiovasculares, utilicen prótesis (stent, marcapasos) o sufran arritmias cardíacas frecuentes, personas medicadas con anticoagulantes, personas con várices en estado avanzado (gruesas y múltiples), personas con discapacidades pulmonares (EPOC, asma, enfisemas, etc.)."},

    {"id":5,"Actividad":"kayak con lobos","descripcion":"¡Reserva con 48 horas de anticipación y prepárate para una experiencia que despertará todos tus sentidos en las aguas del Golfo Nuevo! ¿Te imaginas remando en kayak mientras los lobos marinos juegan a tu alrededor? A las 7:00 hs te pasamos a buscar por tu alojamiento y partimos hacia la Estancia, donde nos equiparemos y prepararemos los kayaks. Te proporcionamos todo lo necesario: remos, chalecos salvavidas, cascos, etc. Antes de comenzar, nuestro guía especializado te dará una charla informativa para garantizar que disfrutes de la actividad con total seguridad, ¡y luego estaremos listos para remar! Tras interactuar desde los kayaks con los curiosos lobos marinos, haremos una pausa para disfrutar de un delicioso almuerzo (incluido), que consta de un sándwich (jamón, queso, tomate, lechuga), fruta, agua y opciones de té, café o sopa. Si tienes requerimientos especiales para el menú, avísanos con anticipación. Con las energías recargadas, nos acercaremos de nuevo al apostadero de lobos marinos, esta vez por tierra, siempre con el objetivo de mantener una interacción respetuosa con su hábitat. Luego de esta fascinante experiencia, regresamos a la zona de partida, preparamos todo y emprendemos el regreso a Puerto Madryn, previsto para las 17:00 hs aproximadamente. Esta excursión es solo apta para personas de entre 15 y 70 años con buen estado físico (consulta el apartado de aptitud física para kayak). Como toda actividad náutica, está sujeta a las condiciones climáticas y podría reprogramarse si es necesario. Las excursiones en kayak, debido a la exigencia física, son aptas solo para personas entre 15 y 70 años de edad con buen estado físico. NO deberán participar: personas con sobrepeso (hasta 1.70 mts - 90 kg, hasta 1.80 mts - 100 kg, hasta 1.90 mts - 120 kg), mujeres embarazadas, personas con cualquier grado o tipo de discapacidad física o mental que afecte su atención, marcha o coordinación, personas que sufran enfermedades cardiovasculares, utilicen prótesis (stent, marcapasos) o sufran arritmias cardíacas frecuentes, personas medicadas con anticoagulantes, personas con várices en estado avanzado (gruesas y múltiples), personas con discapacidades pulmonares (EPOC, asma, enfisemas, etc.)."},

    {"id":6,"actividad":"travesia 4x4 sunset","descripcion":"¡Descubre la emoción de aventurarte por la zona sur de Puerto Madryn a bordo de un vehículo 4x4! Nos embarcamos en una travesía donde la adrenalina del turismo aventura se combina con la serenidad del atardecer patagónico. A medida que el sol comienza a despedirse en el horizonte, entramos en la mágica hora dorada, donde el cielo se tiñe de tonos dorados y anaranjados, ofreciéndonos un espectáculo visual inolvidable. Recorreremos la costa, atravesando acantilados, médanos y caminos desafiantes, todo mientras disfrutamos de la belleza natural de la región. La experiencia culmina con una parada estratégica, donde te deleitaremos con un aperitivo especialmente preparado para despedir el día de la mejor manera posible. ¡La aventura te está esperando!" }

]

@app.route('/paquetes dias completos', methods=['GET'])
def get_paquetes_completos():
    return jsonify(paquetes_dias_completos)

@app.route('/exursiones medio dia', methods=['GET'])
def get_exursiones_dia():
    return jsonify(excursiones_medio_dia)

@app.route('/nautica y aventura', methods=['GET'])
def get_nautica_aventuras():
    return jsonify(nautica_turismo_aventura)


if __name__=='__main__':
    app.run(host='0.0.0.0')


